### ISSUE TITLE
Incorrect information in the tutorial

### ISSUE THREAD

**Issue by Anmol-Singh-Jaggi** [googledrive/PyDrive#49]
In the [documentation tutorial](http://pythonhosted.org/PyDrive/quickstart.html), the information regarding the type of application to be setup in the developer console is wrong.
Instead of "Select ‘Application type’ to be Web application.", it should be "Select ‘Application type’ to be 'Other'."

**Comment by Atrolantra** [comment]
I got it working fine as a web application by following the guide. Were you having a particular issue with getting it up and running?

**Comment by Fjodor42** [comment]
IIRC, wetting as Web Application lets a sort of virtual user access the drive, which is rather impractical when one has purchased additional storage.

At least I ran into that problem, and seem to remember it having something to do with the application type.

**Comment by Anmol-Singh-Jaggi** [comment]
[My code](https://github.com/Anmol-Singh-Jaggi/gDrive-auto-sync/blob/master/gDrive-auto-sync/upload.py) does not work if I set up the project and credential settings exactly as described in that tutorial.
As soon as I execute the script for the first time, I am redirected to the Google authentication page, and on that page, the following error message is displayed:  
```
400. That’s an error.
Error: redirect_uri_mismatch
Application: <project name>
You can email the developer of this application at: <my email>
The redirect URI in the request: http://localhost:8080/ did not match a registered redirect URI.
Learn more
Request Details
    access_type=offline
    scope=https://www.googleapis.com/auth/drive
    response_type=code
    redirect_uri=http://localhost:8080/
    client_id=402487371318-lgb5025sa7jpet5qj5deohnmrj3q9kmg.apps.googleusercontent.com
That’s all we know.
```

**Comment by Atrolantra** [comment]
@Anmol-Singh-Jaggi 
I was having exactly the same issue.
For the Authorized JavaScript origins: `http://localhost:8080` (no slash at the end like the guide says as google won't accept it)
For the Authorized Redirect URIs: `http://localhost:8080/` (exactly as guide says)

Once that's done then save the JSON and rename it appropriately and give it another shot.

@Fjodor42 
I don't quite follow. :(
I'll admit I don't have a great understanding of how this works and how the different application type affects this but isn't it only relevant here for authorisation? Web app = able to authenticate through a web page and then once it's authorised all the meaty stuff just goes through the api. But I could be wrong. :D Also I can't see how you'd run into problems with additional storage since wouldn't this just continue to operate normally as if you hadn't bought extra storage except now you can have more files in your drive which can be operated on by the api?

**Comment by Fjodor42** [comment]
@Atrolantra 
The two things may be unrelated as you say - if so I just happened to experience both problems at once. To clarify, that other problem was files were going to some storage belonging to the application, as opposed to storage belonging to me. As I have ~½TB of backups, needless to say, the default amount wasn't enough.

As said, it might be unrelated, so I shall keep quiet about it in this thread, except for the clarification above.

My apologies for the noise.

**Comment by Anmol-Singh-Jaggi** [comment]
@Atrolantra Thanks! It's working now. It would be better if this was updated in the tutorial as well.
