### ISSUE TITLE
SetContentFile does not flush write buffer for file used before uploading

### ISSUE THREAD

**Issue by RONNCC** [googledrive/PyDrive#50]
as per title - hence you can get invalid files uploaded because the end few mb's are never uploaded 

It doesn't specify if the responsibility of having a fully flushed file is on the caller on the library anywhere I can find in the docs :/

**Comment by RNabel** [comment]
Hi @RONNCC, since you are only passing the filename, and not the file descriptor, it is impossible for the process running python to flush the write buffer of whatever other program is editing the file. 

Only if a SetContentFile would take a file descriptor (fd) instead of a string AND the program editing the file is using the the same fd to edit the file then it may be possible.
