### ISSUE TITLE
Byte order marks are set at the start of my docs

### ISSUE THREAD

**Issue by jeremy-seipelt** [googledrive/PyDrive#67]
It seems that pydrive or google puts BOMs at the start of my files which renders them useless for me .

I hope you guys know how to remove them. I alrdy did research on that and couldnt fix it with command line tools. Maybe there is a option which i can set to remove BOM.

Maybe u can add an option for removing them in future

**Comment by RNabel** [comment]
Thank you for reporting the issue here! Could you please provide more detailed information / steps on how to reproduce your problem? If you have example file content handy, that would be really useful here as well.

The versions of PyDrive published on PyPI and GitHub are passing all unit tests which, among other things, test that the downloaded version of a file is byte-for-byte the same as the file originally uploaded. If you are encountering this error when downloading Google Drive-specific file formats as, for example, txt files, this problem may be resolved by downloading the file in a different format (i.e. specifying a different mime type).

**Comment by jeremy-seipelt** [comment]
Ok I'll explain you what I am doing at first.
I write blog posts with google docs download them with pydrive and push them with git into github.

The documents are saved as 'example.md' and get downloaded as example.md with the mimetype of text/plain.

When this downloaded example.md gets pushed into a github repository a  " · " gets inserted in the first line. 
This centered dot is removed when I delete the bom by changing the encoding to windows1252 which makes the bom visible in my editor(in utf-8 its invisible but still disrupts somehow my syntax highlighting). After a deletion of the Bom the push looks normal.

What you should at to the documentation is mimetypes which are usable by default for the download.

**Comment by RNabel** [comment]
Thank you for detailing your use-case! I'll add a few tests to the test suite to pin-point the location of this issue. From my understanding of BOM you should neither see them nor mess with them, so this is a surprising issue to have. If this is a problem which occurs on all platforms, I will investigate ways to mitigate this issue / add options to the library. 

Are you using some sort of exotic / out-of-date editor?

**Comment by RNabel** [comment]
Issue confirmed, implementing work-around.

**Comment by RNabel** [comment]
Fix for this is now in the [development branch](https://github.com/googledrive/PyDrive/tree/development). Will close this as soon as next minor version released.

**Comment by RNabel** [comment]
Now merged into master. See this [example](https://github.com/googledrive/PyDrive/blob/master/examples/strip_bom_example.py).
