### ISSUE TITLE
Create a copy of the file

### ISSUE THREAD

**Issue by janihur** [googledrive/PyDrive#85]
I need to make copies of a plenty of files.

AFAICS PyDrive doesn't seem to support copy operation:

https://developers.google.com/drive/v2/reference/files/copy

Is that correct ?

The files that should be copied are Google Docs so I can't download/upload.

**Comment by RNabel** [comment]
Hi @janihur, yep unfortunately PyDrive currently doesn't support copying. You can find an example of how to create a copy [here](https://developers.google.com/drive/v2/reference/files/copy#examples). 
If your program already uses PyDrive, just add the example Python function somewhere as a utility, you can get the file title and id as follows:
```python
f = drive.CreateFile()  # i.e. `f` is a Google Drive File object.
file_id = f['id']
file_title = f['title']
service = drive.auth.service
f_copy = copy_file(service, file_id, file_title)
```

Note that the service needs to be authorized, which will definitely be the case after calling drive.CreateFile(), but if you want to call the copy function in a different context you can call `drive.auth.Authorize()` (see [source](https://github.com/googledrive/PyDrive/blob/986ad8fb4f68dde6ffaa7c61c951d9573314dea0/pydrive/auth.py#L61)).

Further, if you want the copy_file helper method to return a PyDrive file object, you can wrap the query results like so:
```python
def copy_file(drive, origin_file_id, copy_title):
  """Copy an existing file.

  Args:
    drive: A PyDrive Drive object.
    origin_file_id: ID of the origin file to copy.
    copy_title: Title of the copy.

  Returns:
    The copied file if successful, None otherwise.
  """
  copied_file = {'title': copy_title}
  try:
    file_data = drive.auth.service.files().copy(
        fileId=origin_file_id, body=copied_file).execute()
    return drive.CreateFile({'id': file_data['id']}

  except errors.HttpError, error:
    print 'An error occurred: %s' % error
  return None
```
Note: the `copy_file` signature changed. Also, if you access the any field from the returned file object it will have to re-fetch the files metadata, as the file is only aware of the id.

**Comment by janihur** [comment]
Thanks for a perfect answer ! 

Yes, indeed I'm using PyDrive. I assume I can use the same pattern with other [Files resources](https://developers.google.com/drive/v2/reference/files) too.

Below a fully functional example script that copies a single file based on `id`.

```python
import argparse

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive

def get_drive_handle():
    gauth = GoogleAuth()
    gauth.LocalWebserverAuth()
    drive = GoogleDrive(gauth)
    return drive

def copy_file(service, source_id, dest_title):
    copied_file = {'title': dest_title}
    f = service.files().copy(fileId=source_id, body=copied_file).execute()
    return f['id']
                            
def main():
    parser = argparse.ArgumentParser(description='Google Drive file copy.')
    parser.add_argument('source_id',
                        help='source file id')
    parser.add_argument('-t', '--title',
                        help='destination title')
    args = parser.parse_args()

    drive = get_drive_handle()

    source = drive.CreateFile({'id': args.source_id})
    source.FetchMetadata('title')

    print(source)

    dest_title = args.title if args.title else source['title']
    dest_id = copy_file(drive.auth.service, args.source_id, dest_title)
    
    dest = drive.CreateFile({'id': dest_id})
    dest.FetchMetadata('title')
    
    print(dest)
    
if __name__ == '__main__':
    main()
```

**Comment by RNabel** [comment]
Awesome, glad I could help! Thank you for providing a full working solution :) If there's demand we may integrate it into the library (in which case I'll let you know if we're using your code).

**Comment by abubelinha** [comment]
> If there's demand we may integrate it into the library 

Thanks @RNabel. I think there is some demand (this was an issue claiming for it). 
I also found some [other people asking for this in StackOverflow](https://stackoverflow.com/questions/43865016/python-copy-a-file-in-google-drive-into-a-specific-folder).
I do also suggest it to be part of the library, since copying files is a common task.

This is my use case:
- A partner has shared a folder with me, with many files inside. My account has access to them, but they are consuming the quota of my partner. And she cannot transfer me their ownership (because these are mostly images, and not original Google Documents like sheets or docs). 
- So my partner expects me to make my own copy of them in my own drive, so I became owner and she can delete the original folders to restore his quota.
- The folder has a tree structure with many subfolders, and I am only interested in the images inside. So there is no easy way to copy its images to my drive, other than programatically (navigating it recursively, checking mimetypes, and so on).

BWT. In case these would have been google Docs or Sheets, is there an easy way to transfer ownership of a Gsheet with PyDrive? (instead of copying them).

Thanks a lot in advance
